"""Convert Valve's OpenXR GLBs and red glove texture into embedded C++ assets.

Requires Python 3 and Pillow. Source downloads and provenance are documented in
assets/valve_hands/README.md. This is an offline tool, not a build dependency.
"""

import argparse
import hashlib
import json
import math
from pathlib import Path
import struct

from PIL import Image


JOINT_NAMES = ["Palm", "Wrist", "Thumb_Metacarpal", "Thumb_Proximal",
               "Thumb_Distal", "Thumb_Tip"]
for finger in ["Index", "Middle", "Ring", "Little"]:
    JOINT_NAMES.extend(finger + "_" + bone for bone in
                       ["Metacarpal", "Proximal", "Intermediate", "Distal", "Tip"])


def read_glb(path):
    data = path.read_bytes()
    magic, version, length = struct.unpack_from("<III", data)
    assert magic == 0x46546C67 and version == 2 and length == len(data)
    json_size, json_type = struct.unpack_from("<II", data, 12)
    assert json_type == 0x4E4F534A
    doc = json.loads(data[20:20 + json_size])
    binary_size, binary_type = struct.unpack_from("<II", data, 20 + json_size)
    assert binary_type == 0x004E4942
    binary = data[28 + json_size:28 + json_size + binary_size]

    def accessor(index):
        a = doc["accessors"][index]
        assert "sparse" not in a and not a.get("normalized", False)
        view = doc["bufferViews"][a["bufferView"]]
        assert view.get("buffer", 0) == 0
        count = {"SCALAR": 1, "VEC2": 2, "VEC3": 3, "VEC4": 4, "MAT4": 16}[a["type"]]
        fmt = "<" + {5121: "B", 5123: "H", 5126: "f"}[a["componentType"]] * count
        stride = view.get("byteStride", struct.calcsize(fmt))
        offset = view.get("byteOffset", 0) + a.get("byteOffset", 0)
        return [struct.unpack_from(fmt, binary, offset + i * stride) for i in range(a["count"])]

    return doc, accessor


def floats(values):
    assert all(math.isfinite(v) for v in values)
    return ", ".join(format(v, ".9e") + "f" for v in values)


def export_hand(path, side, output):
    doc, read = read_glb(path)
    assert len(doc["meshes"]) == len(doc["skins"]) == 1
    mesh_node, = [n for n in doc["nodes"] if "mesh" in n]
    assert mesh_node["skin"] == 0 and all(k not in mesh_node for k in ["matrix", "translation", "rotation", "scale"])
    primitive, = doc["meshes"][0]["primitives"]
    assert primitive.get("mode", 4) == 4
    attributes = primitive["attributes"]
    positions, normals, uvs, joints, weights = [read(attributes[k]) for k in
        ["POSITION", "NORMAL", "TEXCOORD_0", "JOINTS_0", "WEIGHTS_0"]]
    indices = [v[0] for v in read(primitive["indices"])]
    skin = doc["skins"][0]
    suffix = "_L" if side == "left" else "_R"
    assert all(doc["nodes"][i]["name"].endswith(suffix) for i in skin["joints"])
    mapping = [JOINT_NAMES.index(doc["nodes"][i]["name"][:-2])
               for i in skin["joints"]]
    assert sorted(mapping) == list(range(26))
    matrices = [None] * 26
    for joint, matrix in zip(mapping, read(skin["inverseBindMatrices"])):
        matrices[joint] = matrix
    assert len(positions) < 32768 and len(indices) % 3 == 0 and max(indices) < len(positions)
    assert all(len(v) == len(positions) for v in [normals, uvs, joints, weights])
    lines = ["// Generated by tools/import_valve_hands.py; Valve asset license: LICENSE.",
             "// clang-format off", "static constexpr HandModelVertex " + side + "_vertices[] = {"]
    for p, n, uv, js, ws in zip(positions, normals, uvs, joints, weights):
        assert abs(sum(ws) - 1.0) < 0.0001 and all(0 <= w <= 1 for w in ws)
        ws = [w / sum(ws) for w in ws]
        js = [mapping[j] for j in js]
        lines.append("    { { " + floats(p) + " }, { " + floats(n) + " }, { " + floats(uv)
                     + " }, { " + ", ".join(map(str, js)) + " }, { " + floats(ws) + " } },")
    lines.extend(["};", "static constexpr uint16_t " + side + "_indices[] = {"])
    for i in range(0, len(indices), 24):
        lines.append("    " + ", ".join(map(str, indices[i:i + 24])) + ",")
    lines.extend(["};", "static constexpr std::array<float, 16> " + side + "_inverse_bind[] = {"])
    for matrix in matrices:
        lines.append("    { " + floats(matrix) + " },")
    lines.extend(["};", "// clang-format on", ""])
    (output / (side + ".inc")).write_text("\n".join(lines), encoding="utf-8")
    print(side, len(positions), "vertices,", len(indices) // 3, "triangles")


def rgb565(rgb):
    r, g, b = rgb
    return ((r * 31 + 127) // 255 << 11) | ((g * 63 + 127) // 255 << 5) | ((b * 31 + 127) // 255)


def decode565(c):
    return ((c >> 11) * 255 // 31, ((c >> 5) & 63) * 255 // 63, (c & 31) * 255 // 31)


def distance(a, b):
    return sum((x - y) ** 2 for x, y in zip(a, b))


def bc1_block(pixels):
    # Farthest-point endpoints keep this small offline encoder deterministic.
    mean = tuple(sum(p[i] for p in pixels) // 16 for i in range(3))
    a = max(pixels, key=lambda p: distance(p, mean))
    b = max(pixels, key=lambda p: distance(p, a))
    c0, c1 = sorted([rgb565(a), rgb565(b)], reverse=True)
    if c0 == c1:
        if c0 < 65535:
            c0 += 1
        else:
            c1 -= 1
    a, b = decode565(c0), decode565(c1)
    palette = [a, b, tuple((2 * x + y) // 3 for x, y in zip(a, b)),
               tuple((x + 2 * y) // 3 for x, y in zip(a, b))]
    bits = sum(min(range(4), key=lambda i: distance(p, palette[i])) << (2 * j)
               for j, p in enumerate(pixels))
    return c0 | (c1 << 16) | (bits << 32)


def export_texture(path, output):
    image = Image.open(path).convert("RGB").resize((512, 512), Image.LANCZOS)
    blocks, levels = [], []
    while True:
        width, height = image.size
        levels.append((width, height, len(blocks)))
        pixels = image.load()
        for y in range(0, height, 4):
            for x in range(0, width, 4):
                block = [pixels[min(x + dx, width - 1), min(y + dy, height - 1)]
                         for dy in range(4) for dx in range(4)]
                blocks.append(bc1_block(block))
        if width == height == 1:
            break
        image = image.resize((max(1, width // 2), max(1, height // 2)), Image.LANCZOS)
    lines = ["// Generated by tools/import_valve_hands.py; Valve asset license: LICENSE.",
             "// clang-format off", "static constexpr HandTextureLevel texture_levels[] = {"]
    lines.extend("    { %d, %d, %d }," % level for level in levels)
    lines.extend(["};", "static constexpr uint64_t texture_blocks[] = {"])
    for i in range(0, len(blocks), 6):
        lines.append("    " + ", ".join("0x%016xULL" % b for b in blocks[i:i + 6]) + ",")
    lines.extend(["};", "// clang-format on", ""])
    (output / "texture.inc").write_text("\n".join(lines), encoding="utf-8")
    print("Texture:", len(levels), "mips,", len(blocks) * 8, "BC1 bytes")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("source", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()
    args.output.mkdir(parents=True, exist_ok=True)
    for side in ["left", "right"]:
        path = args.source / ("openxr_glove_" + side + "_model_slim.glb")
        print(path.name, "SHA256", hashlib.sha256(path.read_bytes()).hexdigest())
        export_hand(path, side, args.output)
    texture = args.source / "vr_glove_color_red.jpg"
    print(texture.name, "SHA256", hashlib.sha256(texture.read_bytes()).hexdigest())
    export_texture(texture, args.output)
    (args.output / "LICENSE").write_bytes((args.source / "LICENSE").read_bytes())


if __name__ == "__main__":
    main()
